
name: UBC NLP Group
title: UBC NLP Group
tagline: NLP Group at the University of British Columbia
description: The Natural Language Processing (NLP) group at University of British Columbia conducts research on core NLP problems, computational linguistics, text mining, and visual text analytics under Profs. Giuseppe Carenini, Raymond Ng and Vered Shwartz. 
baseurl: ""
url: ""
sponsors:
  - "nserc_logo.png"
  - "huawei_logo.png"
twitter_username: UBC_NLP
github_username:  NLP-UBC
profile:
  image: banner.png
  ubc_logo: ubc.png
  ubc_signature: ubc_dark.png
  nlp_logo: nlp.png
  email: ubc-nlp@cs.ubc.ca
  affiliation: University of British Columbia

include: ['_pages']

scholar:
  locale: en
  bibliography_template: "bib"
  use_raw_bibtex_entry: true
  sort_by: none
  order: ascending
  group_by: none
  group_order: ascending
  bibliography_list_tag: ul

collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  people:
    defaults:
      layout: post
    output: true
    permalink: /people/:path/
  showcase:
    defaults:
      layout: post
    output: true
    permalink: /showcase/:path/

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-seo-tag
  
